// Centralized global usings to reduce per-file boilerplate and avoid unnecessary/useless imports
// Add only broadly used namespaces here. Keep the list conservative to avoid surprising name collisions.
global using System;
global using System.Buffers;
global using System.Collections.Concurrent;
global using System.Collections.Generic;
global using System.ComponentModel.DataAnnotations;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Diagnostics.Metrics;
global using System.Globalization;
global using System.IO.Enumeration;
global using System.Net;
global using System.Net.Http.Headers;
global using System.Runtime.CompilerServices;
global using System.Security.Cryptography;
global using System.Text;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Text.RegularExpressions;
global using System.Threading;
global using System.Threading.Channels;
global using System.Threading.Tasks;
global using FileWatchRest.Configuration;
global using FileWatchRest.Helpers;
global using FileWatchRest.Logging;
global using FileWatchRest.Models;
global using FileWatchRest.Services;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
[assembly: InternalsVisibleTo(assemblyName: "FileWatchRest.Tests")]
